### ISSUE TITLE
Include `package.json` to this project

### ISSUE THREAD

**Issue by rmuslimov** [district0x/district-server-smart-contracts#1]
I'm playing here with your project. Looks great! However, can you please add `package.json`? Since js libraries are very fragile, not everything works on latest version of `web3` for example.
Having explicit requirements for nodejs modules, will help a lot. 

Thanks,

**Comment by madvas** [comment]
Not sure what libraries you mean. We have some npm dependencies listed in project.clj, managed by lein-npm. They're installed by `lein deps`.

**Comment by rmuslimov** [comment]
You're right, I've installed explicitly latest version of web3, and got problem with that.
