### ISSUE TITLE
Is lowercasing placeholder when linking libraries necessary?

### ISSUE THREAD

**Issue by rmuslimov** [district0x/district-server-smart-contracts#3]
I have small problem with linking libraries for trivial example. It's a bit different from way chosen in `name-bazaar`. 

1. Check out this trivial solidity code: https://github.com/rmuslimov/demo-smart-contracts/tree/master/resources/public/contracts/src

2. After compilation sol files, I've got something like: 
`***00073__Bar.sol:Bar___________________________631546aaeb8***` in `Foo.bin` file

3. I tried to deploy code using this:
```
  (contracts/deploy-smart-contract!
   :foo
   {:arguments [(get-admin)]
    :placeholder-replacements {"__Bar.sol:Bar___________________________" :bar}})
```
 https://github.com/rmuslimov/demo-smart-contracts/blob/master/src/demosc/core.cljs#L22-L25

4. And it's actually works, if I drop with `str/lowercase` in your code here: 
```
modified   src/district/server/smart_contracts.cljs
@@ -99,7 +99,7 @@
             (let [address (if (keyword? replacement)
                             (get-in smart-contracts [replacement :address])
                             replacement)]
-              (link-library bin (string/lower-case placeholder) address)))
+              (link-library bin placeholder address)))
           bin library-placeholders))
```

https://github.com/district0x/district-server-smart-contracts/blob/master/src/district/server/smart_contracts.cljs#L102

Could we do that? Will it break something?

**Comment by madvas** [comment]
Ah yeah, you can actually remove `string/lower-case`. It was to lowercase if placeholder is an address, but that's probably not right place to do it there. 
Thanks

**Comment by rmuslimov** [comment]
Thanks!
